name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        run: |
          docker build -t builder . -f- <<EOF
          FROM python:3.11-alpine
          WORKDIR /build
          RUN apk add --no-cache gcc musl-dev linux-headers
          COPY . .
          RUN pip install -r requirements.txt pyinstaller
          RUN pyinstaller --onefile --name server Server.py
          EOF
          docker create --name temp builder
          docker cp temp:/build/dist/server ./server
          docker rm temp
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: server
